language: go
go:
    - 1.12
jobs:
  include:
    -
      stage: 'unit test'
      install:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
      script:
        - 'make test'
        - '$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN'
